### ISSUE TITLE
04-runajob: note about merging

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshopwhepp-lesson-condor#1]
In real-scale processing, even if reduced from the input MiniAOD, the total output volume can be large.

While it makes sense for a small-scale test, merging the output files might not be practical for a full-dataset-scale production.

It requires 2 x disk space at the time of the merge  (probably not an issue), and downloading the big output file becomes problematic.
E.g. at CERN on the eos file system, the maximum file size a normal user can download is 50G.

From what we've seen, the standard "POET" output for a single dataset remains at the level of 15-20G (for those we've processed), but coffea-type processing can be > 50G.

It would be best to offer an example to download the separate files to a local storage, rather than one big merged file.

**Comment by jmhogan** [comment]
Noted -- I've added a callout describing these issues for large files. I think it's still nice to show the functionality of hadd if possible. I've also noted that we should show "scp -r" explicitly.

**Comment by katilp** [comment]
OK, perfect! Note that it is  `hadd` that requires 2 x disk space at the time of the merge. But this time that's probably not an issue if the temporary disk space is not tight in the setup (in contrast to the public cloud in which disk space costs).

Update: that's indeed what you've written 😊 - closing
